dragonlands_movie_user:
    resource: "@DragonlandsMovieBundle/Resources/config/routing/user.yml"
    prefix:   /user

dragonlands_movie_rating:
    resource: "@DragonlandsMovieBundle/Resources/config/routing/rating.yml"
    prefix:   /rating

homepage:
    path:   /
    defaults: { _controller: DragonlandsMovieBundle:Default:index }

newMovie:
    path:   /new
    defaults: { _controller: DragonlandsMovieBundle:Default:new }

deleteMovie:
    path:   /delete/{id}
    defaults: { _controller: DragonlandsMovieBundle:Default:delete }

modifyMovie:
    path:   /modify/{id}
    defaults: { _controller: DragonlandsMovieBundle:Default:modify }

showTags:
    path:   /showTags
    defaults: { _controller: DragonlandsMovieBundle:Tag:index }

newTag:
    path:   /newTag
    defaults: { _controller: DragonlandsMovieBundle:Tag:new }

deleteTag:
    path:   /deleteTag/{id}
    defaults: { _controller: DragonlandsMovieBundle:Tag:delete }

modifyTag:
    path:   /modifyTag/{id}
    defaults: { _controller: DragonlandsMovieBundle:Tag:modify }

getJsonSearchResultsForQuery:
    path:   /getJsonSearchResultsForQuery
    defaults: { _controller: DragonlandsMovieBundle:Tag:getJsonSearchResultsForQuery }
