Dragonlands\MovieBundle\Entity\Movie:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titleOrig:
            type: string
            length: 255
            column: title_orig
        titleDe:
            type: string
            length: 255
            column: title_de
            nullable: true
        year:
            type: integer
            nullable: true
        length:
            type: integer
            nullable: true
        imdbId:
            type: string
            length: 255
            column: imdb_id
            nullable: true
    lifecycleCallbacks: {  }
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: movies
            joinTable:
                name: movies_tags
                joinColumns:
                    movie_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
