Dragonlands\MovieBundle\Entity\Movie:
  type: entity
  repositoryClass: Dragonlands\MovieBundle\Entity\MovieRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    titleOrig:
      type: string
      length: 255
      nullable: true
      column: title_orig
    titleDe:
      type: string
      length: 255
      nullable: true
      column: title_de
    year:
      type: integer
      nullable: true
    length:
      type: integer
      nullable: true
    imdbId:
      type: string
      length: 255
      nullable: true
      column: imdb_id
  # a movie can have several ratings
  oneToMany:
    ratings:
      targetEntity: Dragonlands\MovieBundle\Entity\Rating
      mappedBy: movie
  # a movie has a creator
  manyToOne:
    user:
      targetEntity: User
      inversedBy: movies
      joinColumn:
        name: user_id
        referencedColumnName: id
