Dragonlands\MovieBundle\Entity\Tag:
  type: entity
  repositoryClass: Dragonlands\MovieBundle\Entity\TagRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: true
    color:
      type: string
      length: 6
      nullable: true
  oneToMany:
    ratings:
      targetEntity: Dragonlands\MovieBundle\Entity\Rating
      mappedBy: tag
