Dragonlands\MovieBundle\Entity\User:
  type: entity
  repositoryClass: Dragonlands\MovieBundle\Entity\UserRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 255
      nullable: true
    email:
      type: string
      length: 255
      nullable: true
    passwordhash:
      type: string
      length: 255
      nullable: true
  oneToMany:
    ratings:
      targetEntity: Dragonlands\MovieBundle\Entity\Rating
      mappedBy: user
