Dragonlands\MovieBundle\Entity\User:
  type: entity
  table: user
  repositoryClass: Dragonlands\MovieBundle\Entity\UserRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    comment:
      type: text
      nullable: true
    birthday:
      type: datetime
      nullable: true
  oneToMany:
    movies:
      targetEntity: Movie
      mappedBy: user
    ratings:
      targetEntity: Rating
      mappedBy: user
