Dragonlands\MovieBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Dragonlands\MovieBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        email:
            type: string
            length: 255
        passwordhash:
            type: string
            length: 255
    lifecycleCallbacks: {  }
