Dragonlands\MovieBundle\Entity\User:
  type: entity
  table: fos_user
  repositoryClass: Dragonlands\MovieBundle\Entity\UserRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    comment:
      type: text
      nullable: true
