<?php

namespace Dragonlands\MovieBundle\Entity;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEntityCount()
    {
        
        $qb = $this->createQueryBuilder('u');
        $qb->select('count(u.id)');
        
        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }

}
