<?php

namespace Dragonlands\MovieBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEntityCount()
    {
        
        $qb = $this->createQueryBuilder('u');
        $qb->select('count(u.id)');
        
        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }

    public function findAll()
    {
        return $this->findBy(array(), array('name' => 'ASC'));
    }

}
